from crewai import Task
from src.agents_src.tasks.question_answer_task import AnswerStructure
from src.agents_src.agents.fact_checker_agent import fact_checker_agent

fact_checker_task = Task(
    agent=fact_checker_agent,
    name="Fact Checking and QA Task",
    description="""
    Review the answer generated by the prior agents for the query "{user_query}".

    ===== ORIGINAL DOCUMENT CONTEXT =====
    {retrieved_context}
    ===== END OF CONTEXT =====

    chat_history: "{chat_history}"

    Instructions:
    - Compare the previous agent's answer against the ORIGINAL DOCUMENT CONTEXT above.
    - If the answer is supported by the context, refine it for clarity and professional tone.
    - If ANY claims are NOT supported by the context, correct or remove them.
    - Always output the result strictly in the requested JSON structure.
    """,
    expected_output=""" 
    You MUST return ONLY a valid JSON object. DO NOT include any additional text.
    {
      "answer": "The finalized, fact-checked response.",
      "sources": ["List of source document names from the context"],
      "tool_used": "RAG Pipeline",
      "rationale": "How you verified the facts against the document context."
    }
    """,
    output_pydantic=AnswerStructure,
)
